version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_DATABASE=mobilelele
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
  promtool:
    image: prom/prometheus:v2.31.1
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - 3000:3000
